from PIL import Image
import os, sys

INPUT = "img.png"
OUTPUT_PNG = "img_marked.png"
OUTPUT_PPM = "img_marked.ppm"

EXPECTED_WIDTH = 960
EXPECTED_HEIGHT = 1280

POINTS = [
    ((64, 64, 255), "upper_left"),
    ((255, 255, 64), "upper_right"),
    ((255, 64, 255), "lower_left"),
]

POINT_SIZE = 5

def draw_point(pixels, width, height, x_center, y_center, color, size=1):
    half = size // 2
    for yy in range(y_center - half, y_center - half + size):
        for xx in range(x_center - half, x_center - half + size):
            if 0 <= xx < width and 0 <= yy < height:
                pixels[xx, yy] = color

def save_as_ppm(img, output_file):
    w, h = img.size
    pixels = img.load()

    with open(output_file, "w", encoding="ascii") as f:
        f.write("P3\n")
        f.write(f"# Generated by Lab_1.py\n")
        f.write(f"{w} {h}\n")
        f.write("255\n")

        for y in range(h):
            row_values = []
            for x in range(w):
                r, g, b = pixels[x, y]
                row_values.extend([str(r), str(g), str(b)])
            line = " ".join(row_values)
            while len(line) > 70:
                break_pos = line[:70].rfind(' ')
                if break_pos == -1:
                    break_pos = 70
                f.write(line[:break_pos] + "\n")
                line = line[break_pos+1:]
            if line:
                f.write(line + "\n")

def main():
    if not os.path.exists(INPUT):
        print(f"файл '{INPUT}' не найден в {os.getcwd()}")
        sys.exit(1)

    img = Image.open(INPUT).convert("RGB")
    w, h = img.size

    if (w, h) != (EXPECTED_WIDTH, EXPECTED_HEIGHT):
        print(f"{EXPECTED_WIDTH}x{EXPECTED_HEIGHT}, "
              f"{w}x{h}")

    pixels = img.load()

    coords = {
        "upper_left": (20, 20),
        "upper_right": (w - 20, 20),
        "lower_left": (20, h - 20),
        "lower_right": (w - 20, h - 20),
        "center": (w // 2, h // 2),
    }

    for color, pos_name in POINTS:
        if pos_name not in coords:
            continue
        x, y = coords[pos_name]
        draw_point(pixels, w, h, x, y, color, size=POINT_SIZE)

    img.save(OUTPUT_PNG)

    save_as_ppm(img, OUTPUT_PPM)

if __name__ == "__main__":
    main()
